export const dedicadoPlans = [
  {
    nome: "AMD Ryzen 5 5600X",
    frequencia: "3.7GHz até 4.6GHz",
    disponibilidade: true,
    preco: 1000.0,
    nucleos: 6,
    threads: 12,
    tier: "Essential",
    popular: false,
    link: "https://discord.gg/qN8pH33jdh",
    specs: [
      { icon: "Cpu", label: "6 Núcleos", value: "12 Threads" },
      { icon: "MemoryStick", label: "64GB RAM", value: "DDR5" },
      { icon: "HardDrive", label: "1TB NVMe", value: "Gen4 SSD" },
      { icon: "Network", label: "1Gbps", value: "Uplink" },
      { icon: "ArrowUpFromDot", label: "20TB", value: "Tráfego" },
      { icon: "Shield", label: "DDoS", value: "348TB/s" },
    ],
    recursos: [
      "Hardware 100% dedicado",
      "Acesso root completo",
      "IP dedicado incluído",
      "Painel de controle avançado",
      "Monitoramento 24/7",
      "Suporte técnico prioritário",
      "Migração gratuita",
    ],
    aplicacoes: [
      "Aplicações empresariais",
      "Servidores de jogos",
      "Desenvolvimento e testes",
      "Hospedagem de sites",
      "Bancos de dados",
      "Aplicações web",
    ],
  },
  {
    nome: "AMD Ryzen 7 7700X",
    frequencia: "4.5GHz até 5.4GHz",
    disponibilidade: true,
    preco: 1650.0,
    nucleos: 8,
    threads: 16,
    tier: "Professional",
    popular: true,
    link: "https://discord.gg/qN8pH33jdh",
    specs: [
      { icon: "Cpu", label: "8 Núcleos", value: "16 Threads" },
      { icon: "MemoryStick", label: "128GB RAM", value: "DDR5" },
      { icon: "HardDrive", label: "2TB NVMe", value: "Gen4 SSD" },
      { icon: "Network", label: "1Gbps", value: "Uplink" },
      { icon: "ArrowUpFromDot", label: "20TB", value: "Tráfego" },
      { icon: "Shield", label: "DDoS", value: "348TB/s" },
    ],
    recursos: [
      "Hardware 100% dedicado",
      "Acesso root completo",
      "IP dedicado incluído",
      "Painel de controle avançado",
      "Monitoramento 24/7",
      "Suporte técnico prioritário",
      "Migração gratuita",
      "Configuração personalizada",
      "Consultoria técnica incluída",
    ],
    aplicacoes: [
      "Aplicações enterprise críticas",
      "Servidores de jogos AAA",
      "Machine Learning",
      "Big Data Analytics",
      "Streaming de alta qualidade",
      "Aplicações de alta demanda",
    ],
  },
  {
    nome: "AMD Ryzen 9 7900X",
    frequencia: "4.7GHz até 5.6GHz",
    disponibilidade: true,
    preco: 2000.0,
    nucleos: 12,
    threads: 24,
    tier: "Enterprise",
    popular: false,
    link: "https://discord.gg/qN8pH33jdh",
    specs: [
      { icon: "Cpu", label: "12 Núcleos", value: "24 Threads" },
      { icon: "MemoryStick", label: "128GB RAM", value: "DDR5" },
      { icon: "HardDrive", label: "2TB NVMe", value: "Gen4 SSD" },
      { icon: "Network", label: "1Gbps", value: "Uplink" },
      { icon: "ArrowUpFromDot", label: "40TB", value: "Tráfego" },
      { icon: "Shield", label: "DDoS", value: "348TB/s" },
    ],
    recursos: [
      "Hardware 100% dedicado",
      "Acesso root completo",
      "IP dedicado incluído",
      "Painel de controle avançado",
      "Monitoramento 24/7",
      "Suporte técnico prioritário",
      "Migração gratuita",
      "Configuração personalizada",
      "Consultoria técnica incluída",
      "SLA 99.99% uptime",
      "Gerente de conta dedicado",
    ],
    aplicacoes: [
      "Infraestrutura crítica",
      "Aplicações de missão crítica",
      "Processamento intensivo",
      "Virtualização avançada",
      "Clusters de alta performance",
      "Soluções corporativas",
    ],
  },
]
